[plugin]
name = "chess-map-frontend"
version = "0.1.0"
description = "CHESS Map front-end plugin with glass-morphic UI and Mapbox integration"
entrypoint = "src/main.tsx"

[env]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""
VITE_MAPBOX_TOKEN = ""